#rosalind_reversecomplement
#Objective: produce a DNA complementary strand

'''The question is why we've gotta to reverse?
Note that DNA reading invention is starting from 5-end to 3-end direction.
Only producing the complementary sequence without reversing will result in
a 3-end to 5-end sequence => we would be reading the result in the wrong direction
'''


import os
os.chdir('/home/vu/Downloads/')
d = {'A':'T', 'T':'A', 'C':'G', 'G':'C'}
f = open('rosalind_revc (1).txt', 'r').read()[:-1]
s = ''.join(d[i] for i in f) #3-end to 5-end complementary sequence
s = s[::-1] #reverse the complementary sequence
print s

'''Result
AGCAATTCGTTCCGCCGTAGGAGAATGTTAAATTGTTCCCACGCGGGCCTC
TTACCCTGGGCTATTCCAAGCGCGATACCGTGAGTATCGAAGTCAATTAAT
CCCCCCCGCTTATGCTGATACATCTCTCCGATACCTTGTGCGTGAGTTTGA
ACTGTGAGAAAGAGCGGGCACAATCAGAAGTAATTTGTTTAATTTTTCTCT
ATCGCCCATCACCTTGATAGTGCGGATGCTGCTTACTTAAGTTGCACCGAA
GAGCGGACGATGAGCATCTGCATCTTGCGCGGGACGTGCAGGGTTTCTTGT
ACAGCCCTCAAACTGCATAGCTTCCGGAACTGGCGGCATCATTGTCATGCG
AGTCCTCTTCAGTCGATAACACCACATCCTACGGCTTGTTCCTGAGTCAGC
GCTGGGGCGTCCTGGGATTGTAGCCATCGAGCAAAGGGCGGCGCAGTCGAC
ATTGGCGACTCTCCTACTTAGACGTGTTGCCTTCAACTTTTAATCGGCGCA
ATTCGGCTTATCGCGCTTCTCACAACAGAAGAGGGAACAAGACATGAGAGC
GATAGCTAAGATAGAATATCACGGCCAAGACCGGCGACGTTGCTACACCCC
TAATATTTCTGTGCTAGTCGTCGTGCGATGATATTTATCCCTCCCAAGTTG
GGGTCGGATCATACGGCTAACAGTTGCAATGTACTAGCGACTTGTAAACAT
GCCGAACCCCGAGGCCAGTATGTATAGATGTTACTCCTATCTCCCAAGGTC
CACACTGGAGAGTTCTAGGACTTAGAATATCGCTCCTCTTGTCGGCTATGG
AAGTATGGAAGTGCGCCAATGGGGTTACTCGAGACCGTTGCACAGAAGCAT
TTAATTTAT'''
